# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'graph_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13graph_service.proto\x12\x05graph\"\x1d\n\x08NodeList\x12\x11\n\tneighbors\x18\x01 \x03(\t\"\xa7\x01\n\x12SubmitGraphRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12;\n\tadjacency\x18\x02 \x03(\x0b\x32(.graph.SubmitGraphRequest.AdjacencyEntry\x1a\x41\n\x0e\x41\x64jacencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.graph.NodeList:\x02\x38\x01\"k\n\x13SubmitGraphResponse\x12\x14\n\x0c\x63lient_nodes\x18\x01 \x01(\x05\x12\x14\n\x0c\x63lient_edges\x18\x02 \x01(\x05\x12\x13\n\x0bunion_nodes\x18\x03 \x01(\x05\x12\x13\n\x0bunion_edges\x18\x04 \x01(\x05\"\x13\n\x06QueryK\x12\t\n\x01k\x18\x01 \x01(\x05\"\x17\n\tBoolReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x0e\n\x0cResetRequest\" \n\rResetResponse\x12\x0f\n\x07\x63leared\x18\x01 \x01(\x08\x32\xee\x01\n\x0cGraphService\x12\x44\n\x0bSubmitGraph\x12\x19.graph.SubmitGraphRequest\x1a\x1a.graph.SubmitGraphResponse\x12\x34\n\x11HasIndependentSet\x12\r.graph.QueryK\x1a\x10.graph.BoolReply\x12.\n\x0bHasMatching\x12\r.graph.QueryK\x1a\x10.graph.BoolReply\x12\x32\n\x05Reset\x12\x13.graph.ResetRequest\x1a\x14.graph.ResetResponseB\tZ\x07graphpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007graphpb'
  _globals['_SUBMITGRAPHREQUEST_ADJACENCYENTRY']._loaded_options = None
  _globals['_SUBMITGRAPHREQUEST_ADJACENCYENTRY']._serialized_options = b'8\001'
  _globals['_NODELIST']._serialized_start=30
  _globals['_NODELIST']._serialized_end=59
  _globals['_SUBMITGRAPHREQUEST']._serialized_start=62
  _globals['_SUBMITGRAPHREQUEST']._serialized_end=229
  _globals['_SUBMITGRAPHREQUEST_ADJACENCYENTRY']._serialized_start=164
  _globals['_SUBMITGRAPHREQUEST_ADJACENCYENTRY']._serialized_end=229
  _globals['_SUBMITGRAPHRESPONSE']._serialized_start=231
  _globals['_SUBMITGRAPHRESPONSE']._serialized_end=338
  _globals['_QUERYK']._serialized_start=340
  _globals['_QUERYK']._serialized_end=359
  _globals['_BOOLREPLY']._serialized_start=361
  _globals['_BOOLREPLY']._serialized_end=384
  _globals['_RESETREQUEST']._serialized_start=386
  _globals['_RESETREQUEST']._serialized_end=400
  _globals['_RESETRESPONSE']._serialized_start=402
  _globals['_RESETRESPONSE']._serialized_end=434
  _globals['_GRAPHSERVICE']._serialized_start=437
  _globals['_GRAPHSERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
